// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TPGrupo4.Persistencia;

namespace TPGrupo4.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20241008012554_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("TPGrupo4.Clases.Cliente", b =>
                {
                    b.Property<string>("dni")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("contrasenia")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("domicilioCalle")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("nombreCompleto")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("usuario")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("dni");

                    b.HasIndex("domicilioCalle");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("TPGrupo4.Clases.Domicilio", b =>
                {
                    b.Property<string>("Calle")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Altura")
                        .HasColumnType("int");

                    b.Property<int>("CodigoPostal")
                        .HasColumnType("int");

                    b.Property<bool>("EsCasa")
                        .HasColumnType("bit");

                    b.HasKey("Calle");

                    b.ToTable("Domicilio");
                });

            modelBuilder.Entity("TPGrupo4.Clases.Cliente", b =>
                {
                    b.HasOne("TPGrupo4.Clases.Domicilio", "domicilio")
                        .WithMany()
                        .HasForeignKey("domicilioCalle");

                    b.Navigation("domicilio");
                });
#pragma warning restore 612, 618
        }
    }
}
