// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TPGrupo4.Persistencia;

namespace TPGrupo4.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("TPGrupo4.Clases.Cliente", b =>
                {
                    b.Property<string>("dni")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("contrasenia")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("domicilioCalle")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("nombreCompleto")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("usuario")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("dni");

                    b.HasIndex("domicilioCalle");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("TPGrupo4.Clases.Domicilio", b =>
                {
                    b.Property<string>("Calle")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CodigoPostal")
                        .HasColumnType("int");

                    b.Property<bool>("EsCasa")
                        .HasColumnType("bit");

                    b.HasKey("Calle");

                    b.ToTable("Domicilios");
                });

            modelBuilder.Entity("TPGrupo4.Clases.Objeto", b =>
                {
                    b.Property<int>("idObjeto")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Precio")
                        .HasColumnType("float");

                    b.HasKey("idObjeto");

                    b.ToTable("Objetos");
                });

            modelBuilder.Entity("TPGrupo4.Clases.Venta", b =>
                {
                    b.Property<int>("idVenta")
                        .HasColumnType("int");

                    b.Property<int>("cantObjeto")
                        .HasColumnType("int");

                    b.Property<string>("compradordni")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("fechaCompra")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("itemidObjeto")
                        .HasColumnType("int");

                    b.Property<int>("medioPago")
                        .HasColumnType("int");

                    b.Property<double>("precioTotal")
                        .HasColumnType("float");

                    b.Property<string>("vendedordni")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("idVenta");

                    b.HasIndex("compradordni");

                    b.HasIndex("itemidObjeto");

                    b.HasIndex("vendedordni");

                    b.ToTable("Ventas");
                });

            modelBuilder.Entity("TPGrupo4.Clases.Cliente", b =>
                {
                    b.HasOne("TPGrupo4.Clases.Domicilio", "domicilio")
                        .WithMany()
                        .HasForeignKey("domicilioCalle");

                    b.Navigation("domicilio");
                });

            modelBuilder.Entity("TPGrupo4.Clases.Venta", b =>
                {
                    b.HasOne("TPGrupo4.Clases.Cliente", "comprador")
                        .WithMany()
                        .HasForeignKey("compradordni");

                    b.HasOne("TPGrupo4.Clases.Objeto", "item")
                        .WithMany()
                        .HasForeignKey("itemidObjeto");

                    b.HasOne("TPGrupo4.Clases.Cliente", "vendedor")
                        .WithMany()
                        .HasForeignKey("vendedordni");

                    b.Navigation("comprador");

                    b.Navigation("item");

                    b.Navigation("vendedor");
                });
#pragma warning restore 612, 618
        }
    }
}
